-- 1. Create the assignments table
CREATE TABLE public.asignaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  territorio_id BIGINT REFERENCES public.territorios(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  publisher_name TEXT, -- Denormalized for easier display
  fecha_asignacion TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  fecha_devolucion TIMESTAMPTZ
);

-- 2. Enable RLS for the new table
ALTER TABLE public.asignaciones ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS policies for asignaciones
-- Authenticated users can see all assignments (for history)
CREATE POLICY "Authenticated users can view assignments" ON public.asignaciones
  FOR SELECT USING (auth.role() = 'authenticated');

-- Admins can insert, update, or delete assignments
CREATE POLICY "Admins can manage assignments" ON public.asignaciones
  FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- 4. Create a function to assign a territory
CREATE OR REPLACE FUNCTION assign_territory(territory_id_param BIGINT, user_id_param UUID, publisher_name_param TEXT)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  -- Check if caller is an admin
  IF (SELECT role FROM public.profiles WHERE id = auth.uid()) <> 'admin' THEN
    RAISE EXCEPTION 'Only admins can assign territories.';
  END IF;

  -- Update the territory's state
  UPDATE public.territorios
  SET estado = 'asignado'
  WHERE id = territory_id_param;

  -- Create a new assignment record
  INSERT INTO public.asignaciones (territorio_id, user_id, publisher_name, fecha_asignacion)
  VALUES (territory_id_param, user_id_param, publisher_name_param, NOW());
END;
$$;

-- 5. Create a function to return a territory
CREATE OR REPLACE FUNCTION return_territory(territory_id_param BIGINT)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  latest_assignment_id BIGINT;
BEGIN
  -- Check if caller is an admin
  IF (SELECT role FROM public.profiles WHERE id = auth.uid()) <> 'admin' THEN
    RAISE EXCEPTION 'Only admins can return territories.';
  END IF;

  -- Find the latest, open assignment for this territory
  SELECT id INTO latest_assignment_id
  FROM public.asignaciones
  WHERE territorio_id = territory_id_param AND fecha_devolucion IS NULL
  ORDER BY fecha_asignacion DESC
  LIMIT 1;
  
  -- If an open assignment exists, update it
  IF latest_assignment_id IS NOT NULL THEN
    UPDATE public.asignaciones
    SET fecha_devolucion = NOW()
    WHERE id = latest_assignment_id;
  END IF;

  -- Update the territory's state back to 'disponible'
  UPDATE public.territorios
  SET estado = 'disponible'
  WHERE id = territory_id_param;
END;
$$;
